#ifndef DRIVER_ST7789_INTERFACE_H
#define DRIVER_ST7789_INTERFACE_H

#define SPI_CLOCK_FREQUENCY_HZ 26666666

#define GPIO_PIN_NUM_CS 5
#define GPIO_PIN_NUM_DC 16
#define GPIO_PIN_NUM_RST 23
#define GPIO_PIN_NUM_BCKL 4

#endif
